<a href="https://colab.research.google.com/github/maxforsjoki/quinyx_assignment/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
print(np.random.rand(3,3))

[[0.99433543 0.92942145 0.57332037]
 [0.98656954 0.23233783 0.86139033]
 [0.92917993 0.55936413 0.38001623]]


In [4]:
import sys
print(sys.version)

3.7.12 (default, Jan 15 2022, 18:48:18) 
[GCC 7.5.0]
